### ISSUE TITLE
POST response while creating of entity

### ISSUE THREAD

**Issue by MaksymKmets** [wanderlustking/remCRM#4]
Что вовращать будем когда добавили сушность.
Пока возвращаю саму сушность. Адрес не меняется.
К примеру:
Добавил пользователя : Алексей
Сделал это POST запросом на адрес /users
Будет тот же адрес шяс и вернятся этот же JSON c Алексеем. Как надо?

**Comment by DrewNov** [comment]
Да, саму сущность, + уже заполненный ID параметр, который должен был быть получен в результате создания объекта в БД.
И статус код 200, либо если эррор, то правильный код ошибки (9 пункт):
http://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/

**Comment by MaksymKmets** [comment]
URL менянтся на /users/{ИдАлексея} не должен, как я понимаю?
